const assetDatabase = {
  "categories": [
    {
      "id": "videography",
      "title": "Cinematography",
      "subtitle": "Jamie Pang × Fitmonkie",
      "type": "video",
      "items": [
        { "name": "Fitmonkie_Shoot_01.mp4", "path": "https://drive.google.com/uc?export=view&id=1_1RLXoPudrZMHOihhDHhCqhkD1y0fLLQ" },
        { "name": "Fitmonkie_Shoot_02.mp4", "path": "https://drive.google.com/uc?export=view&id=1tyWkB6MSeemGBpFHDqEvZU87u6517m0j" },
        { "name": "Fitmonkie_Shoot_03.mp4", "path": "https://drive.google.com/uc?export=view&id=1EXyzte4r7FVvBLALnGKtpe3hoDNFIAjY" },
        { "name": "Fitmonkie_Shoot_04.mp4", "path": "https://drive.google.com/uc?export=view&id=1-x_Dc7Vik3YUby5KKAjvnJai0geUTpZx" },
        { "name": "Fitmonkie_Shoot_05.mp4", "path": "https://drive.google.com/uc?export=view&id=1ZB4bBb9kVCdgXzaWxz1OIFrARB-2_SEe" },
        { "name": "Fitmonkie_Shoot_06.mp4", "path": "https://drive.google.com/uc?export=view&id=15jCRrp5iXt6XziICNZKLMZsugeoyRUih" },
        { "name": "Fitmonkie_Shoot_07.mp4", "path": "https://drive.google.com/uc?export=view&id=11d9qP5zGI3mAkg7JBKrgrH8HjFQk5A6d" },
        { "name": "Fitmonkie_Shoot_08.mp4", "path": "https://drive.google.com/uc?export=view&id=13N6nIOHmBaI5IBcpAZ-pyKCtunHt0K0b" },
        { "name": "Fitmonkie_Shoot_09.mp4", "path": "https://drive.google.com/uc?export=view&id=1D55jkRP5Fu5b--kX8I2WYLc86vDljds7" }
      ]
    },
    {
      "id": "events",
      "title": "Events & Action",
      "subtitle": "RHUFT Ultimate Frisbee",
      "type": "mixed",
      "items": [
        { "name": "Frisbee_Match_Highlight.mp4", "path": "https://drive.google.com/uc?export=view&id=1oVUSn-fJGcd2sh5OsZySXcJ3ADBs2Wzz" },
        { "name": "Ultimate_Frisbee_01.jpg", "path": "https://drive.google.com/uc?export=view&id=1sF4pgmZZXOgRn0vc0fgrAchgnijzL-VP" },
        { "name": "Ultimate_Frisbee_02.jpg", "path": "https://drive.google.com/uc?export=view&id=1muguBi7p20BmfD80eunk85-Kw1HViJjT" },
        { "name": "Ultimate_Frisbee_03.jpg", "path": "https://drive.google.com/uc?export=view&id=1tiqR0WIliquAEYIc8OE7DXeTloKC2P-9" },
        { "name": "Ultimate_Frisbee_04.jpg", "path": "https://drive.google.com/uc?export=view&id=11dD5aNmcv-cDIigVY9ps_X5l3qRC7FJZ" },
        { "name": "Ultimate_Frisbee_05.jpg", "path": "https://drive.google.com/uc?export=view&id=1zMXX_wlo8XKtOQk3-bgjCQMCc1Uywqpz" },
        { "name": "Ultimate_Frisbee_06.jpg", "path": "https://drive.google.com/uc?export=view&id=1bREnTe708bQ1DrJyunaT-YV70Q4NbDZ4" },
        { "name": "Ultimate_Frisbee_07.jpg", "path": "https://drive.google.com/uc?export=view&id=1Hyu7Rdg5lygJODOqSgLqf-p7ZGOEytjU" },
        { "name": "Ultimate_Frisbee_08.jpg", "path": "https://drive.google.com/uc?export=view&id=1RyYOYcvGwdlyzfCEGdNH7yQZqSHNg850" },
        { "name": "Ultimate_Frisbee_09.jpg", "path": "https://drive.google.com/uc?export=view&id=1QXaElDHX52yKhdmfdW3sHknrFsgbo-c_" },
        { "name": "Ultimate_Frisbee_10.jpg", "path": "https://drive.google.com/uc?export=view&id=1tlrasMcDb53JlEzEfMtMYT3MWl9c9lfq" },
        { "name": "Ultimate_Frisbee_11.jpg", "path": "https://drive.google.com/uc?export=view&id=1D25qxFVfy9MDnHrBfZQey-CMzjlcRUUZ" },
        { "name": "Ultimate_Frisbee_12.jpg", "path": "https://drive.google.com/uc?export=view&id=1b9YZaVuPZbCFEWNVF1qAXDVB-LXStxzc" }
      ]
    },
    {
      "id": "lifestyle",
      "title": "Lifestyle & Portraits",
      "subtitle": "Off Duty Pilates",
      "type": "photo",
      "items": [
        { "name": "Off_Duty_Pilates_01.jpg", "path": "https://drive.google.com/uc?export=view&id=1RCsOzhvXO4BOHwBX_Y0Df33bfy-nsuga1" },
        { "name": "Off_Duty_Pilates_02.jpg", "path": "https://drive.google.com/uc?export=view&id=ipxQeA9Qp-uJtPb9-JE4RNUmuff3iFFh1" },
        { "name": "Off_Duty_Pilates_03.jpg", "path": "https://drive.google.com/uc?export=view&id=xpKo4aLvYJoRPiI7l_2-a5-QNNuFX5Cz1" },
        { "name": "Off_Duty_Pilates_04.jpg", "path": "https://drive.google.com/uc?export=view&id=ogVbVl02xUiRm8dp-mX6J-OC0lLhs45A1" },
        { "name": "Off_Duty_Pilates_05.jpg", "path": "https://drive.google.com/uc?export=view&id=yhGmi4KnO2k4IVldjZ7b8qGqdE9AeIvu1" },
        { "name": "Off_Duty_Pilates_06.jpg", "path": "https://drive.google.com/uc?export=view&id=Ib_dMhTH3vrAl5MO3vlMAnveqQQqJjyi1" },
        { "name": "Off_Duty_Pilates_07.jpg", "path": "https://drive.google.com/uc?export=view&id=uELRCIDVZ6KFZVC0rLFGITg4-p7YiyMV1" },
        { "name": "Off_Duty_Pilates_08.jpg", "path": "https://drive.google.com/uc?export=view&id=yMjIndg8tEuMc3AKKACGB5lib9_UJCCL1" },
        { "name": "Off_Duty_Pilates_09.jpg", "path": "https://drive.google.com/uc?export=view&id=SRI4zucpRqn8heIm_kui68_9RxZbYtQ6M" },
        { "name": "Off_Duty_Pilates_10.jpg", "path": "https://drive.google.com/uc?export=view&id=10bt8_5I2hcitB0mAKSZBMY-7XJ5tR4NJ" },
        { "name": "Off_Duty_Pilates_11.jpg", "path": "https://drive.google.com/uc?export=view&id=1hVs7nE7F6Tt5O3TmYP3OEQZgbAbSciA1" },
        { "name": "Off_Duty_Pilates_12.jpg", "path": "https://drive.google.com/uc?export=view&id=AbKLrpnclusEwfezr8ZdzFa8m9dPvVNU1" },
        { "name": "Off_Duty_Pilates_13.jpg", "path": "https://drive.google.com/uc?export=view&id=riReuYIP5fqeNF-37KYQ5WSszTCLOa7c1" },
        { "name": "Off_Duty_Pilates_14.jpg", "path": "https://drive.google.com/uc?export=view&id=zhRRMCC30p2Xo-SQ9VINKwcPa_SFFrJf1" },
        { "name": "Off_Duty_Pilates_15.jpg", "path": "https://drive.google.com/uc?export=view&id=D6kI6rc6agqSQKzwrPROG57vkvD45TV1d" },
        { "name": "Off_Duty_Pilates_16.jpg", "path": "https://drive.google.com/uc?export=view&id=_yqfYGaxBPP9ko1n27epDv1e4M2NQ-C1" },
        { "name": "Off_Duty_Pilates_17.jpg", "path": "https://drive.google.com/uc?export=view&id=G5Jn1dBu_NG7D8QKQGgjrJ8F5tI-Utid1" },
        { "name": "Off_Duty_Pilates_18.jpg", "path": "https://drive.google.com/uc?export=view&id=oGO8rxgZhiCvSDsVAbfPPgzy09GWRggB1" },
        { "name": "Off_Duty_Pilates_19.jpg", "path": "https://drive.google.com/uc?export=view&id=6b4lJDDWa8g5tYNqG6gkAKj5U8VvMrVT1" },
        { "name": "Off_Duty_Pilates_20.jpg", "path": "https://drive.google.com/uc?export=view&id=i4It7E0W-r_r-yvJ_RCEuYcEQUfLSBE51" },
        { "name": "Off_Duty_Pilates_21.jpg", "path": "https://drive.google.com/uc?export=view&id=GOmZYO2XGAOeYI5rKqQ2t0C0YsbrrxhJ1" },
        { "name": "Off_Duty_Pilates_22.jpg", "path": "https://drive.google.com/uc?export=view&id=2wJFB50v4J7_ys88JIO72KC7KyO5qlMI1" },
        { "name": "Off_Duty_Pilates_23.jpg", "path": "https://drive.google.com/uc?export=view&id=2ZRYEu-Tef6QVYossvgn7odMYMBHzv1-" },
        { "name": "Off_Duty_Pilates_24.jpg", "path": "https://drive.google.com/uc?export=view&id=oLzJRfkPTJBPqBikB-phA0CY-iVuIOA1" },
        { "name": "Off_Duty_Pilates_25.jpg", "path": "https://drive.google.com/uc?export=view&id=uagelACquGbvFABy7f_mTk-W-Ul-HXQL1" },
        { "name": "Off_Duty_Pilates_26.jpg", "path": "https://drive.google.com/uc?export=view&id=2PGieojyRLzQSicndWca0lCSoBjGysy61" },
        { "name": "Off_Duty_Pilates_27.jpg", "path": "https://drive.google.com/uc?export=view&id=0yD5as4ZhsET_p9gRF2-eQS4XzsF_Ep1V" },
        { "name": "Off_Duty_Pilates_28.jpg", "path": "https://drive.google.com/uc?export=view&id=-Vru2_8Ol5OmE0xP8d56qZA4ycGhe8c1" },
        { "name": "Off_Duty_Pilates_29.jpg", "path": "https://drive.google.com/uc?export=view&id=1VDba_Qr6Yj-7LMkBTWIkZGXGeZyaF_V1" },
        { "name": "Off_Duty_Pilates_30.jpg", "path": "https://drive.google.com/uc?export=view&id=xuDCjwECYVpsdR4J6ouGbqC5tG5C2dEc" }
      ]
    },
    {
      "id": "products",
      "title": "Products & Details",
      "subtitle": "Outdoor Product Shoot",
      "type": "photo",
      "items": [
        { "name": "Outdoor_Product_01.jpg", "path": "https://drive.google.com/uc?export=view&id=1iYSkpgXNY4SFpe_JjhEStuQOGAvoqjm4" },
        { "name": "Outdoor_Product_02.jpg", "path": "https://drive.google.com/uc?export=view&id=1uTDn7_-Cmkq7Nj6RkeHkAG5AH7bGezQs" },
        { "name": "Outdoor_Product_03.jpg", "path": "https://drive.google.com/uc?export=view&id=17bIotdr1yZrc7Fv-64OVh_haV4J1uqrL1" },
        { "name": "Outdoor_Product_04.jpg", "path": "https://drive.google.com/uc?export=view&id=mlcVeBw3qGJDwjzemmZk-bXuYkssZtee1" },
        { "name": "Outdoor_Product_05.jpg", "path": "https://drive.google.com/uc?export=view&id=ZZZZ9snLIZg9k6gvYSYYvUlSRJ8XgCP1w" },
        { "name": "Outdoor_Product_06.jpg", "path": "https://drive.google.com/uc?export=view&id=14GdcyZGaNzRPVFxgHN1XYSfYEUF4AS9_" },
        { "name": "Outdoor_Product_07.jpg", "path": "https://drive.google.com/uc?export=view&id=1d9XXyqMSYyoRHtbjjZpuDE6Da7mENTwk" },
        { "name": "Outdoor_Product_08.jpg", "path": "https://drive.google.com/uc?export=view&id=1KN7zbhF871S6vvNRH9_-UULAZxyrC9hg" },
        { "name": "Outdoor_Product_09.jpg", "path": "https://drive.google.com/uc?export=view&id=1L2Agyiug9zKbrFf-vBZHdsXWdfcrH71Y" },
        { "name": "Outdoor_Product_10.jpg", "path": "https://drive.google.com/uc?export=view&id=1Pe7_Oouu7swAaQBHTnilRyPh5sxc_tUD" },
        { "name": "Outdoor_Product_11.jpg", "path": "https://drive.google.com/uc?export=view&id=1U9E4kv08Xmc7MGflA1C0WQqahGTVJXB0" },
        { "name": "Outdoor_Product_12.jpg", "path": "https://drive.google.com/uc?export=view&id=1seoaCj4JkWJQ9E8lgpyyFuqBqY6VTfP61" },
        { "name": "Outdoor_Product_13.jpg", "path": "https://drive.google.com/uc?export=view&id=fGvu5Js0xoS9ownOWTubiQqhGbHbIV4B" },
        { "name": "Outdoor_Product_14.jpg", "path": "https://drive.google.com/uc?export=view&id=1nY7mxN6u_9xqUFGmar7SO4tA6Yvvlcfi" },
        { "name": "Outdoor_Product_15.jpg", "path": "https://drive.google.com/uc?export=view&id=11FcLvcf8QxpWNl9d-ox8uRWoJoy4helac" },
        { "name": "Outdoor_Product_16.jpg", "path": "https://drive.google.com/uc?export=view&id=11jC514CD2Fe_rq7aw8YPkFm4ffQSbsoX" },
        { "name": "Outdoor_Product_17.jpg", "path": "https://drive.google.com/uc?export=view&id=11n2oP6e0wrUDXc3KwPcSC61u4__tPlqk" },
        { "name": "Outdoor_Product_18.jpg", "path": "https://drive.google.com/uc?export=view&id=C1HaO0d_wWm9xpLEyqBiJFau40glK8oJ" },
        { "name": "Outdoor_Product_19.jpg", "path": "https://drive.google.com/uc?export=view&id=Kd1HjPC9w4ol7DGUM1sd7Q9zFItNiaVI-" },
        { "name": "Outdoor_Product_20.jpg", "path": "https://drive.google.com/uc?export=view&id=V91G6N5IrVKMf34opLu98-5G5c31NnnAA" },
        { "name": "Outdoor_Product_21.jpg", "path": "https://drive.google.com/uc?export=view&id=Pl1Imxo_UA61V3SqrybSpRYhUglgHsn2Y" },
        { "name": "Outdoor_Product_22.jpg", "path": "https://drive.google.com/uc?export=view&id=LR12HA0OQcqKGXHy7YisE8Ndn2zZ3IjHw" },
        { "name": "Outdoor_Product_23.jpg", "path": "https://drive.google.com/uc?export=view&id=6R1ULHHIsrFafj2vcVcUhFEkEat-h3RU8" },
        { "name": "Outdoor_Product_24.jpg", "path": "https://drive.google.com/uc?export=view&id=uW16fKo7s2GHRKLx_NmTItK1nMB6Czjse" },
        { "name": "Outdoor_Product_25.jpg", "path": "https://drive.google.com/uc?export=view&id=an1hV2-TlzdGlSJkl05LLj0nqiNO-M6yT" },
        { "name": "Outdoor_Product_26.jpg", "path": "https://drive.google.com/uc?export=view&id=bG1xAXY1o8mmpt37EH01AfWnr8bWF6GlV" },
        { "name": "Outdoor_Product_27.jpg", "path": "https://drive.google.com/uc?export=view&id=Cb1zgllWCfkmtYogPdfbWE2RU6U_iutP7" },
        { "name": "Outdoor_Product_28.jpg", "path": "https://drive.google.com/uc?export=view&id=cL1q7ZOx0-OdzHkiVba0u5RW2oAReVuvj" },
        { "name": "Outdoor_Product_29.jpg", "path": "https://drive.google.com/uc?export=view&id=YL1pqrLvMsWJXEj8NaxQkOcv_qF8Jz2m7" },
        { "name": "Outdoor_Product_30.jpg", "path": "https://drive.google.com/uc?export=view&id=QH14ba1Yg7FxGgxj3QKy2wReKTIWa8xaq" },
        { "name": "Outdoor_Product_31.jpg", "path": "https://drive.google.com/uc?export=view&id=Oo163_eEdGeVSo_YasVSCSUaFOFGgVmN8" },
        { "name": "Outdoor_Product_32.jpg", "path": "https://drive.google.com/uc?export=view&id=P1nC_neIEYWRxuONeVThlfPA0WYRmkY__" },
        { "name": "Outdoor_Product_33.jpg", "path": "https://drive.google.com/uc?export=view&id=U1Y7akfs2Nwj7eXd4EIQHaNTRSo2d6gOF" },
        { "name": "Outdoor_Product_34.jpg", "path": "https://drive.google.com/uc?export=view&id=y117mw3CKi_deC_FtTTzUPCtXccultS1" },
        { "name": "Outdoor_Product_35.jpg", "path": "https://drive.google.com/uc?export=view&id=a_KjYjz_PbscoQ4X_XWw9qLrZ-4HxV2l1" },
        { "name": "Outdoor_Product_36.jpg", "path": "https://drive.google.com/uc?export=view&id=0_PoALtrK4n9ivJ2iZ6Dglxs_w12UaFz1" },
        { "name": "Outdoor_Product_37.jpg", "path": "https://drive.google.com/uc?export=view&id=yZ8YE2SgAEt-nI2BuKJdzoomsCFmzg88" }
      ]
    }
  ]
};

export default assetDatabase;