const assetDatabase = {
  "categories": [
    {
      "id": "videography",
      "title": "Cinematography",
      "subtitle": "Jamie Pang × Fitmonkie",
      "type": "video",
      "items": [
        { "name": "Fitmonkie_Shoot_01.mp4", "path": "/public/cinematography/Fitmonkie_Shoot_01.mp4" },
        { "name": "Fitmonkie_Shoot_02.mp4", "path": "/public/cinematography/Fitmonkie_Shoot_02.mp4" },
        { "name": "Fitmonkie_Shoot_03.mp4", "path": "/public/cinematography/Fitmonkie_Shoot_03.mp4" },
        { "name": "Fitmonkie_Shoot_04.mp4", "path": "/public/cinematography/Fitmonkie_Shoot_04.mp4" },
        { "name": "Fitmonkie_Shoot_05.mp4", "path": "/public/cinematography/Fitmonkie_Shoot_05.mp4" },
        { "name": "Fitmonkie_Shoot_06.mp4", "path": "/public/cinematography/Fitmonkie_Shoot_06.mp4" },
        { "name": "Fitmonkie_Shoot_07.mp4", "path": "/public/cinematography/Fitmonkie_Shoot_07.mp4" },
        { "name": "Fitmonkie_Shoot_08.mp4", "path": "/public/cinematography/Fitmonkie_Shoot_08.mp4" },
        { "name": "Fitmonkie_Shoot_09.mp4", "path": "/public/cinematography/Fitmonkie_Shoot_09.mp4" }
      ]
    },
    {
      "id": "events",
      "title": "Events & Action",
      "subtitle": "RHUFT Ultimate Frisbee",
      "type": "photo",
      "items": [
        { "name": "Ultimate_Frisbee_01.jpg", "path": "/public/events/Ultimate_Frisbee_01.jpg" },
        { "name": "Ultimate_Frisbee_02.jpg", "path": "/public/events/Ultimate_Frisbee_02.jpg" },
        { "name": "Ultimate_Frisbee_03.jpg", "path": "/public/events/Ultimate_Frisbee_03.jpg" },
        { "name": "Ultimate_Frisbee_04.jpg", "path": "/public/events/Ultimate_Frisbee_04.jpg" },
        { "name": "Ultimate_Frisbee_05.jpg", "path": "/public/events/Ultimate_Frisbee_05.jpg" },
        { "name": "Ultimate_Frisbee_06.jpg", "path": "/public/events/Ultimate_Frisbee_06.jpg" },
        { "name": "Ultimate_Frisbee_07.jpg", "path": "/public/events/Ultimate_Frisbee_07.jpg" },
        { "name": "Ultimate_Frisbee_08.jpg", "path": "/public/events/Ultimate_Frisbee_08.jpg" },
        { "name": "Ultimate_Frisbee_09.jpg", "path": "/events/Ultimate_Frisbee_09.jpg" },
        { "name": "Ultimate_Frisbee_10.jpg", "path": "/public/events/Ultimate_Frisbee_10.jpg" },
        { "name": "Ultimate_Frisbee_11.jpg", "path": "/public/events/Ultimate_Frisbee_11.jpg" },
        { "name": "Ultimate_Frisbee_12.jpg", "path": "/public/events/Ultimate_Frisbee_12.jpg" },
        { "name": "Ultimate_Frisbee_13.jpg", "path": "/public/events/Ultimate_Frisbee_13.jpg" }
      ]
    },
    {
      "id": "lifestyle",
      "title": "Lifestyle & Portraits",
      "subtitle": "Off Duty Pilates",
      "type": "photo",
      "items": [
        { "name": "Off_Duty_Pilates_01.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_01.jpg" },
        { "name": "Off_Duty_Pilates_02.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_02.jpg" },
        { "name": "Off_Duty_Pilates_03.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_03.jpg" },
        { "name": "Off_Duty_Pilates_04.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_04.jpg" },
        { "name": "Off_Duty_Pilates_05.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_05.jpg" },
        { "name": "Off_Duty_Pilates_06.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_06.jpg" },
        { "name": "Off_Duty_Pilates_07.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_07.jpg" },
        { "name": "Off_Duty_Pilates_08.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_08.jpg" },
        { "name": "Off_Duty_Pilates_09.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_09.jpg" },
        { "name": "Off_Duty_Pilates_10.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_10.jpg" },
        { "name": "Off_Duty_Pilates_11.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_11.jpg" },
        { "name": "Off_Duty_Pilates_12.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_12.jpg" },
        { "name": "Off_Duty_Pilates_13.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_13.jpg" },
        { "name": "Off_Duty_Pilates_14.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_14.jpg" },
        { "name": "Off_Duty_Pilates_15.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_15.jpg" },
        { "name": "Off_Duty_Pilates_16.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_16.jpg" },
        { "name": "Off_Duty_Pilates_17.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_17.jpg" },
        { "name": "Off_Duty_Pilates_18.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_18.jpg" },
        { "name": "Off_Duty_Pilates_19.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_19.jpg" },
        { "name": "Off_Duty_Pilates_20.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_20.jpg" },
        { "name": "Off_Duty_Pilates_21.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_21.jpg" },
        { "name": "Off_Duty_Pilates_22.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_22.jpg" },
        { "name": "Off_Duty_Pilates_23.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_23.jpg" },
        { "name": "Off_Duty_Pilates_24.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_24.jpg" },
        { "name": "Off_Duty_Pilates_25.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_25.jpg" },
        { "name": "Off_Duty_Pilates_26.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_26.jpg" },
        { "name": "Off_Duty_Pilates_27.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_27.jpg" },
        { "name": "Off_Duty_Pilates_28.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_28.jpg" },
        { "name": "Off_Duty_Pilates_29.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_29.jpg" },
        { "name": "Off_Duty_Pilates_30.jpg", "path": "/public/lifestyle/Off_Duty_Pilates_30.jpg" }
      ]
    },
    {
      "id": "products",
      "title": "Products & Details",
      "subtitle": "Outdoor Product Shoot",
      "type": "photo",
      "items": [
        { "name": "Outdoor_Product_01.jpg", "path": "/public/products/Outdoor_Product_01.jpg" },
        { "name": "Outdoor_Product_02.jpg", "path": "/public/products/Outdoor_Product_02.jpg" },
        { "name": "Outdoor_Product_03.jpg", "path": "/public/products/Outdoor_Product_03.jpg" },
        { "name": "Outdoor_Product_04.jpg", "path": "/public/products/Outdoor_Product_04.jpg" },
        { "name": "Outdoor_Product_05.jpg", "path": "/public/products/Outdoor_Product_05.jpg" },
        { "name": "Outdoor_Product_06.jpg", "path": "/public/products/Outdoor_Product_06.jpg" },
        { "name": "Outdoor_Product_07.jpg", "path": "/public/products/Outdoor_Product_07.jpg" },
        { "name": "Outdoor_Product_08.jpg", "path": "/public/products/Outdoor_Product_08.jpg" },
        { "name": "Outdoor_Product_09.jpg", "path": "/public/products/Outdoor_Product_09.jpg" },
        { "name": "Outdoor_Product_10.jpg", "path": "/public/products/Outdoor_Product_10.jpg" },
        { "name": "Outdoor_Product_11.jpg", "path": "/public/products/Outdoor_Product_11.jpg" },
        { "name": "Outdoor_Product_12.jpg", "path": "/public/products/Outdoor_Product_12.jpg" },
        { "name": "Outdoor_Product_13.jpg", "path": "/public/products/Outdoor_Product_13.jpg" },
        { "name": "Outdoor_Product_14.jpg", "path": "/public/products/Outdoor_Product_14.jpg" },
        { "name": "Outdoor_Product_15.jpg", "path": "/public/products/Outdoor_Product_15.jpg" },
        { "name": "Outdoor_Product_16.jpg", "path": "/public/products/Outdoor_Product_16.jpg" },
        { "name": "Outdoor_Product_17.jpg", "path": "/public/products/Outdoor_Product_17.jpg" },
        { "name": "Outdoor_Product_18.jpg", "path": "/public/products/Outdoor_Product_18.jpg" },
        { "name": "Outdoor_Product_19.jpg", "path": "/public/products/Outdoor_Product_19.jpg" },
        { "name": "Outdoor_Product_20.jpg", "path": "/public/products/Outdoor_Product_20.jpg" },
        { "name": "Outdoor_Product_21.jpg", "path": "/public/products/Outdoor_Product_21.jpg" },
        { "name": "Outdoor_Product_22.jpg", "path": "/public/products/Outdoor_Product_22.jpg" },
        { "name": "Outdoor_Product_23.jpg", "path": "/public/products/Outdoor_Product_23.jpg" },
        { "name": "Outdoor_Product_24.jpg", "path": "/public/products/Outdoor_Product_24.jpg" },
        { "name": "Outdoor_Product_25.jpg", "path": "/public/products/Outdoor_Product_25.jpg" },
        { "name": "Outdoor_Product_26.jpg", "path": "/public/products/Outdoor_Product_26.jpg" },
        { "name": "Outdoor_Product_27.jpg", "path": "/public/products/Outdoor_Product_27.jpg" },
        { "name": "Outdoor_Product_28.jpg", "path": "/public/products/Outdoor_Product_28.jpg" },
        { "name": "Outdoor_Product_29.jpg", "path": "/public/products/Outdoor_Product_29.jpg" },
        { "name": "Outdoor_Product_30.jpg", "path": "/public/products/Outdoor_Product_30.jpg" },
        { "name": "Outdoor_Product_31.jpg", "path": "/public/products/Outdoor_Product_31.jpg" },
        { "name": "Outdoor_Product_32.jpg", "path": "/public/products/Outdoor_Product_32.jpg" },
        { "name": "Outdoor_Product_33.jpg", "path": "/public/products/Outdoor_Product_33.jpg" },
        { "name": "Outdoor_Product_34.jpg", "path": "/public/products/Outdoor_Product_34.jpg" },
        { "name": "Outdoor_Product_35.jpg", "path": "/public/products/Outdoor_Product_35.jpg" },
        { "name": "Outdoor_Product_36.jpg", "path": "/public/products/Outdoor_Product_36.jpg" }
      ]
    }
  ]
};

export default assetDatabase;